# Generated by Django 5.0.4 on 2024-04-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_url', models.CharField(max_length=300, unique=True)),
                ('short_url', models.CharField(max_length=5, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
